#!/bin/sh
echo -e "$(tput setaf 2)$(tput setab 7)RUNNING APT-UPDATE$(tput sgr 0)"
apt update
echo -e "$(tput setaf 2)$(tput setab 7)INSTALLING APACHE$(tput sgr 0)"
apt install apache2
echo -e "$(tput setaf 2)$(tput setab 7)INSTALLING MYQSL SERVER$(tput sgr 0)"
apt install mysql-server
echo -e "$(tput setaf 2)$(tput setab 7)RUNNING MYSQL-SERVER INSTALLATION$(tput sgr 0)"
mysql_secure_installation
echo -e "$(tput setaf 2)$(tput setab 7)INSTALLING PHP$(tput sgr 0)"
apt install php-pear php-fpm php-dev php-zip php-curl php-xmlrpc php-gd php-mysql
echo -e "$(tput setaf 2)$(tput setab 7)RESTARTING APACHE$(tput sgr 0)"
service apache2 restart
exit
