#!/bin/sh
echo "\n$(tput setaf 1)$(tput setab 7)RUNNING APT-UPDATE$(tput sgr 0)\n"
sudo apt update
echo "\n$(tput setaf 1)$(tput setab 7)INSTALLING APACHE$(tput sgr 0)\n"
sudo apt install apache2
echo "\n$(tput setaf 1)$(tput setab 7)INSTALLING MYQSL SERVER$(tput sgr 0)\n"
sudo apt install mysql-server
echo "\n$(tput setaf 1)$(tput setab 7)RUNNING MYSQL-SERVER INSTALLATION$(tput sgr 0)\n"
sudo mysql_secure_installation
echo "\n$(tput setaf 1)$(tput setab 7)INSTALLING PHP$(tput sgr 0)\n"
sudo apt install php-pear php-fpm php-dev php-zip php-curl php-xmlrpc php-gd php-mysql
echo "\n$(tput setaf 1)$(tput setab 7)RESTARTING APACHE$(tput sgr 0)\n"
sudo service apache2 restart
exit
