#!/bin/sh
COLOR_GREEN='\032[0;32m'
COLOR_NONE='\033[0m'
echo -e "${COLOR_GREEN}RUNNING APT-UPDATE${COLOR_NONE}"
apt update
echo -e "${COLOR_GREEN}INSTALLING APACHE${COLOR_NONE}"
apt install apache2
echo -e "${COLOR_GREEN}INSTALLING MYSQL SERVER${COLOR_NONE}"
apt install mysql-server
echo -e "${COLOR_GREEN}RUNNING MYSQL SERVER INSTALLER${COLOR_NONE}"
mysql_secure_installation
echo -e "${COLOR_GREEN}INSTALLING PHP${COLOR_NONE}"
apt install php-pear php-fpm php-dev php-zip php-curl php-xmlrpc php-gd php-mysql
echo -e "${COLOR_GREEN}RESTARTING APACHE${COLOR_NONE}"
service apache2 restart
exit
